# PROPRIETARY AND CONFIDENTIAL  
# THIS SOFTWARE IS THE SOLE PROPERTY AND COPYRIGHT © 2019 OF ROCKLEY PHOTONICS LTD. 
# USE OR REPRODUCTION IN PART OR AS A WHOLE WITHOUT THE WRITTEN AGREEMENT OF ROCKLEY PHOTONICS LTD IS PROHIBITED.
